# -*- coding: utf-8 -*-
"""Inference_AgeGender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBX-3V6M3O0jZG-6t9lpliVy2auOez2g
"""

pip install onnxruntime

import onnxruntime
import numpy as np
from PIL import Image
import torchvision.transforms as T
import torch
import cv2
import os
from google.colab.patches import cv2_imshow


ONNX_MODEL_PATH = "/content/drive/MyDrive/Future_Project/WEIGHT gender + age/model_agegender.onnx"
TEST_IMAGE_PATH = "/content/full-bo-anh-dan-ong-trung-nien-viet-nam-dep-nhat-vn-37.jpg"


HAARCASCADE_PATH = "haarcascade_frontalface_default.xml"
if not os.path.exists(HAARCASCADE_PATH):
    print("Đang tải file Haarcascade...")
    import requests
    url = "https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml"
    r = requests.get(url, allow_redirects=True)
    with open(HAARCASCADE_PATH, 'wb') as f:
        f.write(r.content)
    print("Tải xong!")

face_cascade = cv2.CascadeClassifier(HAARCASCADE_PATH)


IMG_SIZE = 224
AGE_CLASS_OFFSET = 3
GENDER_INV_MAP = {0: "Nam", 1: "Nữ"}

def make_eval_transform(img_size):
    return T.Compose([
        T.Resize((img_size, img_size)),
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])



def predict_age_gender_with_face_detection(model_path, image_path):
    try:

        session = onnxruntime.InferenceSession(model_path, providers=['CPUExecutionProvider'])


        input_name = session.get_inputs()[0].name
        output_names = [output.name for output in session.get_outputs()]

        image_cv = cv2.imread(image_path)
        if image_cv is None:
            print(f"Lỗi: Không thể đọc ảnh từ đường dẫn: {image_path}")
            return

        gray = cv2.cvtColor(image_cv, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.1, 4)

        if len(faces) == 0:
            print("Không tìm thấy khuôn mặt nào trong ảnh!")
            return


        transform = make_eval_transform(IMG_SIZE)
        for i, (x, y, w, h) in enumerate(faces):

            face_crop_cv = image_cv[y:y+h, x:x+w]

            face_crop_pil = Image.fromarray(cv2.cvtColor(face_crop_cv, cv2.COLOR_BGR2RGB))


            input_tensor = transform(face_crop_pil).unsqueeze(0).numpy()


            outputs = session.run(output_names, {input_name: input_tensor})

            age_class_logits = outputs[0]
            age_reg_output = outputs[1]
            gender_logits = outputs[2]


            pred_age_reg = age_reg_output.item()

            pred_remapped_class = np.argmax(age_class_logits, axis=1)[0]
            pred_original_class = pred_remapped_class + AGE_CLASS_OFFSET
            predicted_age = (pred_original_class * 5) + pred_age_reg

            pred_gender_idx = np.argmax(gender_logits, axis=1)[0]
            predicted_gender = GENDER_INV_MAP.get(pred_gender_idx, "Không xác định")


            print(f"\n✅ KẾT QUẢ DỰ ĐOÁN (Khuôn mặt #{i+1}):")
            print(f"   - Tuổi dự đoán: {predicted_age:.2f}")
            print(f"   - Giới tính dự đoán: {predicted_gender}")

            label = f"Age: {predicted_age:.1f}, Gender: {predicted_gender.split(' ')[0]}"
            cv2.rectangle(image_cv, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv2.putText(image_cv, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

        print("\nHiển thị ảnh với các khuôn mặt đã được nhận diện:")
        cv2_imshow(image_cv)

    except Exception as e:
        print(f"Đã xảy ra lỗi trong quá trình dự đoán: {e}")


predict_age_gender_with_face_detection(ONNX_MODEL_PATH, TEST_IMAGE_PATH)

